services:
  - type: web
    name: tayeur-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: tayeur-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://tayeur-frontend.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: tayeur-db
    databaseName: tayeur
    user: tayeur
    plan: free
