# Generated by Django 5.0.2 on 2025-08-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='phone',
            field=models.CharField(blank=True, help_text="Numéro de téléphone de l'atelier", max_length=15),
        ),
    ]
