# Generated by Django 5.0.2 on 2025-08-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workshop_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text="Liste des spécialités de l'atelier (optionnel)", null=True),
        ),
    ]
